name: interfood_case
version: "1.0.0"
profile: interfood_case

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  interfood_case:
    staging:
      +materialized: view
    marts:
      +materialized: table